from django.conf.urls.defaults import *

urlpatterns = patterns('phennyfyxata.scores.views',
        url(r'^$', 'goToWars'),
        url(r'^writers/(?P<nickname>.+)/overview/$', 'singleWriterOverview'),
        url('^writers/$', 'writersOverview'),
        url('^wars/$', 'warsOverview'),
        url('^wars/(?P<war_id>\d+)/overview/$', 'singleWarOverview'),
        url('^wars/(?P<war_id>\d+)/info/$', 'singleWarInfo'),
        url('^api/score/register/$', 'registerScore'),
        url('^api/score/deregister/$', 'deregisterScore'),
        url('^api/war/new/$', 'createWar'),
        url('^api/war/active/$', 'activeWars'),
        url('^api/war/planned/$', 'plannedWars'),
        url('^api/war/(?P<war_id>\d+)/withdraw/$', 'withdrawWar'),
        url('^api/war/(?P<war_id>\d+)/participate/$', 'participateWar'),
        url('^api/war/(?P<war_id>\d+)/listparticipants/$', 'listWarParticipants'),
        url('^documentation/$', 'documentation'),
        url('^documentation/nl/$', 'documentationDutch'),
        url('^language/$', 'language'),
    )
